In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
from datetime import timedelta

In [111]:
demand_factors_daily = pd.read_csv("demand factors/demand_factors_daily.csv")
financial_factors_daily = pd.read_csv("financial factors/daily_financial_factors.csv")
implied_vol_indices_daily = pd.read_csv("implied vol indices/daily_implied_volatility_indices.csv")
brent_daily = pd.read_csv("prices/daily_realized_volatility_Brent.csv")
supply_factors_daily = pd.read_csv("supply factors/daily_oil_data.csv")
uncertainty_factors_daily = pd.read_csv("uncertainty factors/uncertainty factors daily.csv")

In [112]:
demand_factors_daily = demand_factors_daily.set_index("Date")
financial_factors_daily = financial_factors_daily.set_index("Date")
implied_vol_indices_daily = implied_vol_indices_daily.set_index("Date")
brent_daily = brent_daily.set_index("Date")
supply_factors_daily = supply_factors_daily.set_index("Date")
uncertainty_factors_daily = uncertainty_factors_daily.set_index("Date")

In [113]:
daily_dataset = pd.merge(demand_factors_daily, financial_factors_daily, on = "Date")
daily_dataset = pd.merge(daily_dataset, implied_vol_indices_daily, on = "Date")
daily_dataset = pd.merge(daily_dataset, brent_daily, on = "Date")
daily_dataset = pd.merge(daily_dataset, supply_factors_daily, on = "Date")
daily_dataset = pd.merge(daily_dataset, uncertainty_factors_daily, on = "Date")

In [114]:
daily_dataset = pd.concat([demand_factors_daily, financial_factors_daily])
daily_dataset = pd.concat([daily_dataset, implied_vol_indices_daily])
daily_dataset = pd.concat([daily_dataset, brent_daily])
daily_dataset = pd.concat([daily_dataset, supply_factors_daily])
daily_dataset = pd.concat([daily_dataset, uncertainty_factors_daily])

In [115]:
daily_dataset = daily_dataset.fillna(0)

In [116]:
daily_dataset = daily_dataset.iloc[64396:,:]
daily_dataset

,Imports_US,Imports_SPR,PPI_commodity,Consumption_US,GBPUSD=X,GC=F,HG=F,JPY=X,USDEUR=X,ZW=F,...,Taxes,Government Spending,Health Care,National Security,Entitlement programs,Regulation,Financial Regulation,Trade Policy,"Sovereign debt, currency crises",US Policy Uncertainty Index
Date,,,,,,,,,,,,,,,,,,,,,
2023-02-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2023-02-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2023-02-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2023-02-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2023-02-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-07-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.997676,11.643674,24.120781,12.594630,23.710592,21.247733,11.072076,153.256542,2.890518,16.911940
2025-08-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.653484,8.418171,20.877801,12.279955,17.984860,12.235830,7.244518,123.961528,0.472820,16.860247
2025-09-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,18.498564,10.394802,24.883883,10.725879,23.915877,10.481822,4.994681,171.246877,1.385426,14.538229
2025-10-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,18.834881,11.037099,35.054845,13.392293,32.969814,14.853939,5.839378,116.752884,3.023492,14.070908
2025-11-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.551080,14.429557,26.626952,12.860967,31.555698,12.869644,4.042397,145.526842,1.681921,14.660322

In [121]:
rev_daily = pd.read_csv("prices/daily_realized_volatility_WTI.csv")
rev_daily.set_index("Date", inplace = True)

In [122]:
rev_daily

            RV_WTI_day
Date
1987-05-21    1.007565
1987-05-22    1.362625
1987-05-23    0.000000
1987-05-24    0.000000
1987-05-25    0.000000
...                ...
2025-11-27    0.000000
2025-11-28    0.000000
2025-11-29    0.000000
2025-11-30    0.000000
2025-12-01    1.507864

[14075 rows x 1 columns]

RIDGE

In [123]:
from sklearn.linear_model import Ridge

In [132]:
model_ridge = Ridge(max_iter=10000, alpha=1.0, solver="auto", random_state=42)
model_ridge.fit(daily_dataset, rev_daily)
model_ridge.predict(daily_dataset)

array([1.21560757, 1.21560757, 1.10051243, ..., 0.74323759, 0.68983328,
       0.78899925], shape=(14075,))

In [133]:
model_ridge

Ridge(max_iter=10000, random_state=42)

LASSO

In [130]:
from sklearn.linear_model import Lasso

In [134]:
model_lasso = Lasso(max_iter=10000, alpha=0.1, random_state=42)
model_lasso.fit(daily_dataset, rev_daily)
model_lasso.predict(daily_dataset)
model_lasso

Lasso(alpha=0.1, max_iter=10000, random_state=42)

ELASTIC NET

In [135]:
from sklearn.linear_model import ElasticNet

In [136]:
model_elastic = ElasticNet(max_iter=10000, alpha=0.1, l1_ratio=0.5, random_state=42)
model_elastic.fit(daily_dataset, rev_daily)
model_elastic.predict(daily_dataset)
model_elastic

ElasticNet(alpha=0.1, max_iter=10000, random_state=42)