In [4]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import datetime as dt
from datetime import timedelta
import yfinance as yf
import seaborn as sns
import openpyxl

- oro  GC = F
- rame  HG = F
- grano  ZW = F

In [14]:
ticker = ["^GSPC", "USDEUR=X", "JPY=X", "GBPUSD=X", "HG=F", "ZW=F", "GC=F"]

end = dt.datetime.now()
start = end - dt.timedelta(days = 365 * 45)


data = yf.download(ticker, start , end)["Close"].pct_change().dropna()
data

C:\Users\miche\AppData\Local\Temp\ipykernel_40904\3208802216.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, start , end)["Close"].pct_change().dropna()
[*********************100%***********************]  7 of 7 completed
C:\Users\miche\AppData\Local\Temp\ipykernel_40904\3208802216.py:7: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  data = yf.download(ticker, start , end)["Close"].pct_change().dropna()

Ticker,GBPUSD=X,GC=F,HG=F,JPY=X,USDEUR=X,ZW=F,^GSPC
Date,,,,,,,
2003-12-02,0.006817,0.002483,0.014652,-0.004030,-0.010254,-0.005505,-0.003271
2003-12-03,-0.001279,0.000495,0.006704,-0.003955,-0.002805,0.020295,-0.001772
2003-12-04,-0.004284,-0.001486,-0.013320,-0.000277,0.003479,-0.009042,0.004687
2003-12-05,0.007210,0.007687,0.006231,-0.006003,-0.008698,-0.018856,-0.007684
2003-12-08,0.000642,0.000492,-0.002580,-0.001951,-0.002706,0.015499,0.007348
...,...,...,...,...,...,...,...
2025-12-09,0.000165,0.004657,-0.023115,0.003244,-0.000105,0.000466,-0.000876
2025-12-10,-0.001745,-0.002449,0.006679,0.006378,0.001129,-0.009324,0.006750
2025-12-11,0.006373,0.021233,0.028718,-0.006682,-0.006233,0.006118,0.002079
2025-12-12,0.000161,0.003407,-0.026442,-0.001431,-0.003253,0.000000,0.000000
2025-12-15,0.000040,0.013488,0.022712,-0.003767,-0.001444,-0.016838,-0.006683

In [15]:
daily_data = data
daily_data

Ticker,GBPUSD=X,GC=F,HG=F,JPY=X,USDEUR=X,ZW=F,^GSPC
Date,,,,,,,
2003-12-02,0.006817,0.002483,0.014652,-0.004030,-0.010254,-0.005505,-0.003271
2003-12-03,-0.001279,0.000495,0.006704,-0.003955,-0.002805,0.020295,-0.001772
2003-12-04,-0.004284,-0.001486,-0.013320,-0.000277,0.003479,-0.009042,0.004687
2003-12-05,0.007210,0.007687,0.006231,-0.006003,-0.008698,-0.018856,-0.007684
2003-12-08,0.000642,0.000492,-0.002580,-0.001951,-0.002706,0.015499,0.007348
...,...,...,...,...,...,...,...
2025-12-09,0.000165,0.004657,-0.023115,0.003244,-0.000105,0.000466,-0.000876
2025-12-10,-0.001745,-0.002449,0.006679,0.006378,0.001129,-0.009324,0.006750
2025-12-11,0.006373,0.021233,0.028718,-0.006682,-0.006233,0.006118,0.002079
2025-12-12,0.000161,0.003407,-0.026442,-0.001431,-0.003253,0.000000,0.000000
2025-12-15,0.000040,0.013488,0.022712,-0.003767,-0.001444,-0.016838,-0.006683

In [17]:
weekly_data = data.resample("W").mean()
weekly_data

Ticker,GBPUSD=X,GC=F,HG=F,JPY=X,USDEUR=X,ZW=F,^GSPC
Date,,,,,,,
2003-12-07,0.002116,0.002295,0.003567,-0.003566,-0.004569,-0.003277,-0.002010
2003-12-14,0.001639,0.001490,0.003606,0.000129,-0.001498,-0.004768,0.002394
2003-12-21,0.002045,-0.000083,0.007933,0.000057,-0.001713,0.000462,0.002707
2003-12-28,0.000776,0.001512,0.000141,-0.000482,-0.000755,-0.014617,0.001327
2004-01-04,0.002439,0.001650,0.003213,-0.001003,-0.002393,0.022163,0.002301
...,...,...,...,...,...,...,...
2025-11-23,-0.001021,-0.000525,-0.001588,0.003519,0.001684,0.000074,-0.003882
2025-11-30,0.002381,0.006864,0.007029,-0.001380,-0.001126,0.001532,0.007358
2025-12-07,0.001224,-0.000236,0.007565,-0.001463,-0.000737,0.002461,0.000626
2025-12-14,0.001033,0.004150,-0.003482,0.000557,-0.001648,-0.001106,0.000895
2025-12-21,0.000040,0.013488,0.022712,-0.003767,-0.001444,-0.016838,-0.006683

In [18]:
monthly_data = data.resample("M").mean()
monthly_data

C:\Users\miche\AppData\Local\Temp\ipykernel_40904\3673507981.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_data = data.resample("M").mean()

Ticker,GBPUSD=X,GC=F,HG=F,JPY=X,USDEUR=X,ZW=F,^GSPC
Date,,,,,,,
2003-12-31,0.001828,0.001456,0.004033,-0.000736,-0.002305,-0.003326,0.001759
2004-01-31,0.000949,-0.001417,0.004276,-0.000710,0.000483,0.001673,0.000801
2004-02-29,0.001227,-0.000663,0.008211,0.001657,-0.000076,-0.000926,0.000622
2004-03-31,-0.000580,0.003314,0.000727,-0.002029,0.000671,0.003295,-0.000674
2004-04-30,-0.001597,-0.004420,-0.005012,0.002636,0.001264,-0.002890,-0.000742
...,...,...,...,...,...,...,...
2025-08-31,0.000909,0.002581,0.002068,-0.000761,-0.001027,-0.000423,0.000927
2025-09-30,-0.000238,0.004614,0.002869,0.000566,-0.000184,-0.000770,0.001588
2025-10-31,-0.000904,0.001786,0.002496,0.001544,0.000597,0.002224,0.001011
2025-11-30,0.000317,0.002946,0.001246,0.000776,-0.000115,-0.000173,0.000107
2025-12-31,0.001030,0.003005,0.003920,-0.000754,-0.001215,-0.000915,0.000084

In [19]:
fed_funds = pd.read_excel("C:\\Users\\miche\\OneDrive\\Documenti\\PROJECTS\\crude oil forecasting\\financial_factors\\fed_funds_rate.xlsx", engine = "openpyxl")

In [20]:
fed_funds.columns = ["Date", "Fed_Funds_Rate"]
fed_funds["Date"] = pd.to_datetime(fed_funds["Date"])
fed_funds.set_index("Date", inplace=True)
fed_funds

            Fed_Funds_Rate
Date
1954-07-01            0.80
1954-08-01            1.22
1954-09-01            1.07
1954-10-01            0.85
1954-11-01            0.83
...                    ...
2025-07-01            4.33
2025-08-01            4.33
2025-09-01            4.22
2025-10-01            4.09
2025-11-01            3.88

[857 rows x 1 columns]

DAILY

In [37]:
fed_funds_daily = fed_funds.resample("D").ffill().reset_index()
fed_funds_daily.set_index("Date", inplace = True)
fed_funds_daily = fed_funds_daily / 22 
fed_funds_daily

            Fed_Funds_Rate
Date
1954-07-01        0.036364
1954-07-02        0.036364
1954-07-03        0.036364
1954-07-04        0.036364
1954-07-05        0.036364
...                    ...
2025-10-28        0.185909
2025-10-29        0.185909
2025-10-30        0.185909
2025-10-31        0.185909
2025-11-01        0.176364

[26057 rows x 1 columns]

In [40]:
data_daily = pd.merge(daily_data, fed_funds_daily, on = "Date")

In [41]:
data_daily

,GBPUSD=X,GC=F,HG=F,JPY=X,USDEUR=X,ZW=F,^GSPC,Fed_Funds_Rate
Date,,,,,,,,
2003-12-02,0.006817,0.002483,0.014652,-0.004030,-0.010254,-0.005505,-0.003271,0.044545
2003-12-03,-0.001279,0.000495,0.006704,-0.003955,-0.002805,0.020295,-0.001772,0.044545
2003-12-04,-0.004284,-0.001486,-0.013320,-0.000277,0.003479,-0.009042,0.004687,0.044545
2003-12-05,0.007210,0.007687,0.006231,-0.006003,-0.008698,-0.018856,-0.007684,0.044545
2003-12-08,0.000642,0.000492,-0.002580,-0.001951,-0.002706,0.015499,0.007348,0.044545
...,...,...,...,...,...,...,...,...
2025-10-27,-0.000381,-0.028288,0.009227,0.003008,-0.001173,0.026341,0.012290,0.185909
2025-10-28,0.001397,-0.008921,0.000000,-0.002411,-0.001721,0.005703,0.002288,0.185909
2025-10-29,-0.004623,0.004412,0.018092,-0.006294,-0.000524,0.006144,-0.000044,0.185909
2025-10-30,-0.006321,0.004418,-0.029712,0.006531,0.004698,-0.015031,-0.009905,0.185909
2025-10-31,-0.002750,-0.004773,-0.002462,0.007713,0.002669,0.018598,0.002618,0.185909

In [45]:
data_daily.to_csv('daily_financial_factors.csv')

WEEKLY

In [ ]:
fed_funds_week = fed_funds.resample("W").ffill().reset_index()
fed_funds_week.set_index("Date", inplace = True)
fed_funds_week = fed_funds_week / 4
fed_funds_week

            Fed_Funds_Rate
Date
1954-07-04          0.2000
1954-07-11          0.2000
1954-07-18          0.2000
1954-07-25          0.2000
1954-08-01          0.3050
...                    ...
2025-10-05          1.0225
2025-10-12          1.0225
2025-10-19          1.0225
2025-10-26          1.0225
2025-11-02          0.9700

[3723 rows x 1 columns]

In [43]:
weekly_vol = pd.merge(weekly_data, fed_funds_week, on = "Date")

In [44]:
weekly_vol

,GBPUSD=X,GC=F,HG=F,JPY=X,USDEUR=X,ZW=F,^GSPC,Fed_Funds_Rate
Date,,,,,,,,
2003-12-07,0.002116,0.002295,0.003567,-0.003566,-0.004569,-0.003277,-0.002010,0.2450
2003-12-14,0.001639,0.001490,0.003606,0.000129,-0.001498,-0.004768,0.002394,0.2450
2003-12-21,0.002045,-0.000083,0.007933,0.000057,-0.001713,0.000462,0.002707,0.2450
2003-12-28,0.000776,0.001512,0.000141,-0.000482,-0.000755,-0.014617,0.001327,0.2450
2004-01-04,0.002439,0.001650,0.003213,-0.001003,-0.002393,0.022163,0.002301,0.2500
...,...,...,...,...,...,...,...,...
2025-10-05,0.001649,0.005551,0.014225,-0.003642,-0.001065,-0.001677,0.002162,1.0225
2025-10-12,-0.002109,0.004969,-0.008216,0.007796,0.002731,-0.006568,-0.004841,1.0225
2025-10-19,0.002108,0.010713,0.003716,-0.003743,-0.002283,0.002109,0.003407,1.0225
2025-10-26,-0.001763,-0.002930,0.006564,0.003290,0.001402,0.003491,0.003819,1.0225
2025-11-02,-0.002536,-0.006630,-0.000971,0.001710,0.000790,0.008351,0.001450,0.9700

In [46]:
weekly_vol.to_csv('weekly_financial_factors.csv')

MONTHLY

In [47]:
fed_funds_month = fed_funds.resample("M").ffill().reset_index()
fed_funds_month.set_index("Date", inplace = True)
fed_funds_month

C:\Users\miche\AppData\Local\Temp\ipykernel_40904\610055252.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  fed_funds_month = fed_funds.resample("M").ffill().reset_index()

            Fed_Funds_Rate
Date
1954-07-31            0.80
1954-08-31            1.22
1954-09-30            1.07
1954-10-31            0.85
1954-11-30            0.83
...                    ...
2025-07-31            4.33
2025-08-31            4.33
2025-09-30            4.22
2025-10-31            4.09
2025-11-30            3.88

[857 rows x 1 columns]

In [49]:
month_vol = pd.merge(monthly_data, fed_funds_month, on = "Date")

In [50]:
month_vol

,GBPUSD=X,GC=F,HG=F,JPY=X,USDEUR=X,ZW=F,^GSPC,Fed_Funds_Rate
Date,,,,,,,,
2003-12-31,0.001828,0.001456,0.004033,-0.000736,-0.002305,-0.003326,0.001759,0.98
2004-01-31,0.000949,-0.001417,0.004276,-0.000710,0.000483,0.001673,0.000801,1.00
2004-02-29,0.001227,-0.000663,0.008211,0.001657,-0.000076,-0.000926,0.000622,1.01
2004-03-31,-0.000580,0.003314,0.000727,-0.002029,0.000671,0.003295,-0.000674,1.00
2004-04-30,-0.001597,-0.004420,-0.005012,0.002636,0.001264,-0.002890,-0.000742,1.00
...,...,...,...,...,...,...,...,...
2025-07-31,-0.001482,0.000013,-0.004794,0.001407,0.001130,-0.000360,0.000940,4.33
2025-08-31,0.000909,0.002581,0.002068,-0.000761,-0.001027,-0.000423,0.000927,4.33
2025-09-30,-0.000238,0.004614,0.002869,0.000566,-0.000184,-0.000770,0.001588,4.22
2025-10-31,-0.000904,0.001786,0.002496,0.001544,0.000597,0.002224,0.001011,4.09
2025-11-30,0.000317,0.002946,0.001246,0.000776,-0.000115,-0.000173,0.000107,3.88

In [51]:
month_vol.to_csv('monthly_financial_factors.csv')