In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import yfinance as yf
import datetime as dt
from datetime import timedelta

In [5]:
demand_factors_monthly = pd.read_csv("demand factors/demand_factors_monthly.csv")
financial_factors_monthly = pd.read_csv("financial factors/monthly_financial_factors.csv")
implied_vol_indices_monthly = pd.read_csv("implied vol indices/monthly_implied_volatility_indices.csv")
brent_monthly = pd.read_csv("prices/monthly_realized_volatility_Brent.csv")
supply_factors_monthly = pd.read_csv("supply factors/monthly_supply_factors.csv")
uncertainty_factors_monthly = pd.read_csv("uncertainty factors/uncertainty factors monthly.csv")

In [6]:
demand_factors_monthly = demand_factors_monthly.set_index("Date")
financial_factors_monthly = financial_factors_monthly.set_index("Date")
implied_vol_indices_monthly = implied_vol_indices_monthly.set_index("Date")
brent_monthly = brent_monthly.set_index("Date")
supply_factors_monthly = supply_factors_monthly.set_index("Date")
uncertainty_factors_monthly = uncertainty_factors_monthly.set_index("Date")

In [7]:
monthly_dataset = pd.merge(demand_factors_monthly, financial_factors_monthly, on = "Date")
monthly_dataset = pd.merge(monthly_dataset,implied_vol_indices_monthly , on = "Date")
monthly_dataset = pd.merge(monthly_dataset, brent_monthly, on = "Date")
monthly_dataset = pd.merge(monthly_dataset, supply_factors_monthly, on = "Date")
monthly_dataset = pd.merge(monthly_dataset, uncertainty_factors_monthly, on = "Date")

In [8]:
monthly_dataset

,Imports_US,Imports_SPR,PPI_commodity,Consumption_US,GBPUSD=X,GC=F,HG=F,JPY=X,USDEUR=X,ZW=F,...,Taxes,Government Spending,Health Care,National Security,Entitlement programs,Regulation,Financial Regulation,Trade Policy,"Sovereign debt, currency crises",US Policy Uncertainty Index
Date,,,,,,,,,,,,,,,,,,,,,
2008-06-30,0.0,0.0,0.0,20342.00,0.000258,0.002159,0.003461,0.000298,-0.000616,0.005388,...,81.699163,27.504220,60.659855,70.877583,55.342027,129.306143,44.786614,43.103073,0.000000,89.136883
2008-07-31,0.0,0.0,0.0,20156.25,-0.000210,-0.000505,-0.001916,0.000723,0.000476,-0.003017,...,85.538474,53.967210,97.029869,81.483681,92.336940,166.196629,315.213622,28.957536,50.870704,115.102724
2008-08-31,0.0,0.0,0.0,20276.20,-0.004020,-0.004479,-0.003598,0.000444,0.002952,0.000457,...,86.954568,63.542933,107.118918,77.389360,76.554444,89.631373,92.284417,40.370646,6.205545,81.163078
2008-09-30,0.0,0.0,0.0,19020.50,-0.000953,0.002848,-0.007542,-0.001066,0.002023,-0.005711,...,115.814084,80.866261,115.846889,152.949365,88.508892,286.389731,877.545946,30.550760,25.045802,238.171874
2008-10-31,9972.0,0.0,0.0,18945.60,-0.004361,-0.008305,-0.017517,-0.002721,0.005018,-0.009614,...,262.055543,170.974380,274.953898,193.726133,183.037580,328.525415,729.529086,63.263960,160.169448,241.772278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-31,0.0,0.0,0.0,20093.75,0.001274,0.004608,0.005211,-0.000112,-0.001908,0.000122,...,642.230552,526.668070,602.542923,646.921147,749.046363,385.295367,409.310140,5912.107657,119.772697,446.303163
2025-04-30,0.0,0.0,0.0,19658.25,0.001735,0.002890,-0.004078,-0.002340,-0.002385,-0.002082,...,738.800593,370.924816,713.754439,765.615369,688.937014,443.262680,401.195091,7955.646982,508.724945,724.936086
2025-05-31,0.0,0.0,0.0,19822.80,0.000309,-0.000071,0.001018,0.000506,0.000060,0.001963,...,634.201703,622.652256,912.076013,537.533208,984.949127,466.946380,133.018748,5780.037066,98.391385,563.984213
2025-06-30,0.0,0.0,0.0,20288.25,0.000782,0.000133,0.003809,0.000258,-0.001428,-0.000288,...,529.569406,533.527886,677.348277,293.749698,821.004834,400.578002,170.506734,3537.469868,378.361561,375.585314
2025-07-31,0.0,0.0,0.0,20801.00,-0.001482,0.000013,-0.004794,0.001407,0.001130,-0.000360,...,483.948871,256.160825,530.657179,277.081863,521.633035,467.450115,243.585677,3371.643927,63.591386,372.062673

In [12]:
y = pd.read_csv("prices/monthly_realized_volatility_WTI.csv")
y.set_index("Date", inplace=True)

In [16]:
y = y.tail(206)
y

            RV_WTI_month
Date
2008-11-30     24.875430
2008-12-31     34.776274
2009-01-31     25.476082
2009-02-28     22.839778
2009-03-31     23.457647
...                  ...
2025-08-31      6.021164
2025-09-30      7.317334
2025-10-31      8.062434
2025-11-30      4.746575
2025-12-31      1.507864

[206 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet

In [2]:
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    return {"Mean Squared Error": mse, "Mean Absolute Error": mae, "R^2 Score": r2}

In [17]:
lin_model_ridge = Ridge(alpha=1.0)
lin_model_ridge.fit(monthly_dataset, y)
metrics_ridge = evaluate_model(lin_model_ridge, monthly_dataset, y)
metrics_ridge

{'Mean Squared Error': 44.37736108851121,
 'Mean Absolute Error': 3.894226644560409,
 'R^2 Score': 0.2447310705622665}

In [18]:
lin_model_lasso = Lasso(alpha=0.1)
lin_model_lasso.fit(monthly_dataset, y)
metrics_lasso = evaluate_model(lin_model_lasso, monthly_dataset, y)
metrics_lasso

c:\Users\miche\OneDrive\Documenti\PROJECTS\crude oil forecasting\crude_oil_ml\venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.373e+03, tolerance: 1.210e+00
  model = cd_fast.enet_coordinate_descent(

{'Mean Squared Error': 44.45171380121231,
 'Mean Absolute Error': 3.867048132450364,
 'R^2 Score': 0.24346564394957215}

In [19]:
lin_model_elastic = ElasticNet(alpha=0.1, l1_ratio=0.5)
lin_model_elastic.fit(monthly_dataset, y)
metrics_elastic = evaluate_model(lin_model_elastic, monthly_dataset, y)
metrics_elastic

c:\Users\miche\OneDrive\Documenti\PROJECTS\crude oil forecasting\crude_oil_ml\venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.459e+03, tolerance: 1.210e+00
  model = cd_fast.enet_coordinate_descent(

{'Mean Squared Error': 44.426407534483324,
 'Mean Absolute Error': 3.8710460031929306,
 'R^2 Score': 0.2438963373597175}

In [20]:
X_train, X_test, y_train, y_test = train_test_split(monthly_dataset, y, test_size=0.2, random_state=42)
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train.values.ravel())
metrics_rf = evaluate_model(rf_model, X_test, y_test)
metrics_rf

{'Mean Squared Error': 93.99899529131895,
 'Mean Absolute Error': 4.6886675901674035,
 'R^2 Score': 0.014257351977750354}

In [21]:
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)
metrics_dt = evaluate_model(dt_model, X_test, y_test)
metrics_dt

{'Mean Squared Error': 227.75729807102974,
 'Mean Absolute Error': 6.82579037894563,
 'R^2 Score': -1.388430657276012}

SUPPORT VECTOR MACHINE

In [22]:
from sklearn.svm import SVR
from sklearn.metrics import accuracy_score

In [23]:
svm_model = SVR(kernel='rbf', C=100, gamma=0.1, epsilon=.1)
svm_model.fit(X_train, y_train.values.ravel())
svm_metrics = evaluate_model(svm_model, X_test, y_test)
svm_metrics

{'Mean Squared Error': 95.46859606861042,
 'Mean Absolute Error': 4.434129682735815,
 'R^2 Score': -0.001153963401241187}

In [26]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neural_network import MLPRegressor

In [27]:
model_ann = Pipeline([
    ('scaler', StandardScaler()),       
    ('ann', MLPRegressor(hidden_layer_sizes=(50, 25), activation='relu', solver='adam', max_iter=1000, random_state=42))
    ])
model_ann.fit(X_train, y_train.values.ravel())
ann_metrics = evaluate_model(model_ann, X_test, y_test)
ann_metrics

c:\Users\miche\OneDrive\Documenti\PROJECTS\crude oil forecasting\crude_oil_ml\venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:780: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

{'Mean Squared Error': 90.63946295263679,
 'Mean Absolute Error': 5.635696370929796,
 'R^2 Score': 0.04948788070186716}