In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import datetime as dt
from datetime import timedelta

In [3]:
data = pd.read_excel("C:\\Users\\miche\\OneDrive\\Documenti\\PROJECTS\\crude oil forecasting\\uncertainty factors\\US_Policy_Uncertainty_Data.xlsx" )

In [4]:
data.dropna(inplace = True)
data["Month"] = data["Month"].apply(lambda x : int(x))
data["Date"] = data["Year"].astype(str) + "-" + data["Month"].astype(str) + "-01"
data["Date"] = pd.to_datetime(data["Date"])

In [5]:
data.drop(columns = ["Year", "Month"], inplace = True)
data.set_index("Date", inplace = True)
data.sort_index(ascending = False, inplace = True)

In [6]:
data.columns = ["US Policy Uncertainty Index"]

In [7]:
data

            US Policy Uncertainty Index
Date
2025-11-01                   322.527087
2025-10-01                   309.559976
2025-09-01                   319.841041
2025-08-01                   370.925425
2025-07-01                   372.062673
...                                 ...
1900-05-01                    89.715352
1900-04-01                    87.036990
1900-03-01                   166.519786
1900-02-01                   121.120392
1900-01-01                   139.906192

[1511 rows x 1 columns]

In [8]:
import openpyxl

categorical = pd.read_excel("C:\\Users\\miche\\OneDrive\\Documenti\\PROJECTS\\crude oil forecasting\\uncertainty factors\\Categorical_EPU_Data.xlsx", engine = 'openpyxl')

In [9]:
categorical.dropna(inplace = True)
categorical["Month"] = categorical["Month"].apply(lambda x : int(x))
categorical["Date"] = categorical["Year"].astype(str) + "-" + categorical["Month"].astype(str) + "-01"
categorical["Date"] = pd.to_datetime(categorical["Date"])
categorical.drop(columns = ["Year", "Month"], inplace = True)
categorical.set_index("Date", inplace = True)

In [10]:
categorical.drop(columns = ["1. Economic Policy Uncertainty"], inplace = True)

In [11]:
categorical.columns = ["Monetary Policy", "Fiscal Policy", "Taxes", "Government Spending", "Health Care", "National Security", "Entitlement programs", "Regulation", "Financial Regulation", "Trade Policy", "Sovereign debt, currency crises"]

In [12]:
categorical

,Monetary Policy,Fiscal Policy,Taxes,Government Spending,Health Care,National Security,Entitlement programs,Regulation,Financial Regulation,Trade Policy,"Sovereign debt, currency crises"
Date,,,,,,,,,,,
1985-01-01,270.469228,292.614556,295.790786,394.099747,107.848241,179.699854,258.346221,129.632820,113.247177,122.613960,0.000000
1985-02-01,219.835677,164.235536,139.125596,225.032780,36.733030,124.859498,82.492997,55.191052,0.000000,41.762223,128.388997
1985-03-01,119.034522,108.828815,115.714342,102.026340,31.642944,63.269264,113.699141,85.577836,149.521522,107.925728,110.598167
1985-04-01,122.044760,104.737331,85.760217,138.080529,38.066636,85.627432,51.292760,60.054521,44.968804,194.752867,0.000000
1985-05-01,107.573580,134.839967,132.177769,167.568909,54.705931,109.383122,98.284429,65.756140,129.250207,124.391659,95.603868
...,...,...,...,...,...,...,...,...,...,...,...
2025-07-01,342.210478,447.404459,483.948871,256.160825,530.657179,277.081863,521.633035,467.450115,243.585677,3371.643927,63.591386
2025-08-01,288.029857,322.081266,344.376658,185.199769,459.311629,270.159013,395.666913,269.188258,159.379404,2727.153607,10.402046
2025-09-01,374.764422,375.563448,406.968412,228.685637,547.445423,235.969337,526.149304,230.600091,109.882986,3767.431290,30.479367
2025-10-01,244.988901,391.469406,414.367378,242.816177,771.206581,294.630438,725.335919,326.786663,128.466311,2568.563450,66.516825
2025-11-01,245.586122,424.786890,452.123757,317.450247,585.792933,282.941282,694.225351,283.132167,88.932725,3201.590517,37.002268

MONTHLY

In [13]:
uncert_index_month = data.resample("M").mean()

C:\Users\miche\AppData\Local\Temp\ipykernel_50672\3828979758.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  uncert_index_month = data.resample("M").mean()

In [14]:
categorical_month = categorical.resample("M").mean()

C:\Users\miche\AppData\Local\Temp\ipykernel_50672\104292262.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  categorical_month = categorical.resample("M").mean()

In [15]:
uncertainty_factors_monthly = pd.merge(categorical_month, uncert_index_month, on = "Date")

In [16]:
uncertainty_factors_monthly.to_csv("uncertainty factors monthly.csv")

WEEKLY

In [17]:
uncert_index_week = data.resample("W").mean()
#uncert_index_week.dropna(inplace = True)

In [18]:
uncert_index_week = uncert_index_week.apply(lambda x: x / 5).fillna(method='ffill')

C:\Users\miche\AppData\Local\Temp\ipykernel_50672\137293394.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  uncert_index_week = uncert_index_week.apply(lambda x: x / 5).fillna(method='ffill')

In [19]:
categorical_week = categorical.resample("W").mean()
categorical_week = categorical_week.apply(lambda x: x / 5).ffill()
categorical_week

,Monetary Policy,Fiscal Policy,Taxes,Government Spending,Health Care,National Security,Entitlement programs,Regulation,Financial Regulation,Trade Policy,"Sovereign debt, currency crises"
Date,,,,,,,,,,,
1985-01-06,54.093846,58.522911,59.158157,78.819949,21.569648,35.939971,51.669244,25.926564,22.649435,24.522792,0.000000
1985-01-13,54.093846,58.522911,59.158157,78.819949,21.569648,35.939971,51.669244,25.926564,22.649435,24.522792,0.000000
1985-01-20,54.093846,58.522911,59.158157,78.819949,21.569648,35.939971,51.669244,25.926564,22.649435,24.522792,0.000000
1985-01-27,54.093846,58.522911,59.158157,78.819949,21.569648,35.939971,51.669244,25.926564,22.649435,24.522792,0.000000
1985-02-03,43.967135,32.847107,27.825119,45.006556,7.346606,24.971900,16.498599,11.038210,0.000000,8.352445,25.677799
...,...,...,...,...,...,...,...,...,...,...,...
2025-10-05,48.997780,78.293881,82.873476,48.563235,154.241316,58.926088,145.067184,65.357333,25.693262,513.712690,13.303365
2025-10-12,48.997780,78.293881,82.873476,48.563235,154.241316,58.926088,145.067184,65.357333,25.693262,513.712690,13.303365
2025-10-19,48.997780,78.293881,82.873476,48.563235,154.241316,58.926088,145.067184,65.357333,25.693262,513.712690,13.303365
2025-10-26,48.997780,78.293881,82.873476,48.563235,154.241316,58.926088,145.067184,65.357333,25.693262,513.712690,13.303365
2025-11-02,49.117224,84.957378,90.424751,63.490049,117.158587,56.588256,138.845070,56.626433,17.786545,640.318103,7.400454

In [20]:
uncertainty_factors_weekly = pd.merge(categorical_week, uncert_index_week, on = "Date")
uncertainty_factors_weekly.to_csv("uncertainty factors weekly.csv")

In [28]:
uncertainty_factors_weekly

,Monetary Policy,Fiscal Policy,Taxes,Government Spending,Health Care,National Security,Entitlement programs,Regulation,Financial Regulation,Trade Policy,"Sovereign debt, currency crises",US Policy Uncertainty Index
Date,,,,,,,,,,,,
1985-01-06,54.093846,58.522911,59.158157,78.819949,21.569648,35.939971,51.669244,25.926564,22.649435,24.522792,0.000000,20.749761
1985-01-13,54.093846,58.522911,59.158157,78.819949,21.569648,35.939971,51.669244,25.926564,22.649435,24.522792,0.000000,20.749761
1985-01-20,54.093846,58.522911,59.158157,78.819949,21.569648,35.939971,51.669244,25.926564,22.649435,24.522792,0.000000,20.749761
1985-01-27,54.093846,58.522911,59.158157,78.819949,21.569648,35.939971,51.669244,25.926564,22.649435,24.522792,0.000000,20.749761
1985-02-03,43.967135,32.847107,27.825119,45.006556,7.346606,24.971900,16.498599,11.038210,0.000000,8.352445,25.677799,15.662639
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-05,48.997780,78.293881,82.873476,48.563235,154.241316,58.926088,145.067184,65.357333,25.693262,513.712690,13.303365,61.911995
2025-10-12,48.997780,78.293881,82.873476,48.563235,154.241316,58.926088,145.067184,65.357333,25.693262,513.712690,13.303365,61.911995
2025-10-19,48.997780,78.293881,82.873476,48.563235,154.241316,58.926088,145.067184,65.357333,25.693262,513.712690,13.303365,61.911995
2025-10-26,48.997780,78.293881,82.873476,48.563235,154.241316,58.926088,145.067184,65.357333,25.693262,513.712690,13.303365,61.911995
2025-11-02,49.117224,84.957378,90.424751,63.490049,117.158587,56.588256,138.845070,56.626433,17.786545,640.318103,7.400454,64.505417

DAILY

In [21]:
uncertainy_index_daily = data.resample("D").mean()

In [22]:
uncertainy_index_daily = uncertainy_index_daily.apply(lambda x: x / 22).fillna(method='ffill')

C:\Users\miche\AppData\Local\Temp\ipykernel_50672\2038668345.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  uncertainy_index_daily = uncertainy_index_daily.apply(lambda x: x / 22).fillna(method='ffill')

In [23]:
uncertainy_index_daily

            US Policy Uncertainty Index
Date
1900-01-01                     6.359372
1900-01-02                     6.359372
1900-01-03                     6.359372
1900-01-04                     6.359372
1900-01-05                     6.359372
...                                 ...
2025-10-28                    14.070908
2025-10-29                    14.070908
2025-10-30                    14.070908
2025-10-31                    14.070908
2025-11-01                    14.660322

[45961 rows x 1 columns]

In [24]:
categorical_day = categorical.resample("D").mean()
categorical_day = categorical.apply(lambda x : x / 22)

In [25]:
uncertainty_factors_daily = pd.merge(categorical_day, uncertainy_index_daily, on = "Date")

In [26]:
uncertainty_factors_daily

,Monetary Policy,Fiscal Policy,Taxes,Government Spending,Health Care,National Security,Entitlement programs,Regulation,Financial Regulation,Trade Policy,"Sovereign debt, currency crises",US Policy Uncertainty Index
Date,,,,,,,,,,,,
1985-01-01,12.294056,13.300662,13.445036,17.913625,4.902193,8.168175,11.743010,5.892401,5.147599,5.573362,0.000000,4.715855
1985-02-01,9.992531,7.465252,6.323891,10.228763,1.669683,5.675432,3.749682,2.508684,0.000000,1.898283,5.835864,3.559691
1985-03-01,5.410660,4.946764,5.259743,4.637561,1.438316,2.875876,5.168143,3.889902,6.796433,4.905715,5.027189,4.580067
1985-04-01,5.547489,4.760788,3.898192,6.276388,1.730302,3.892156,2.331489,2.729751,2.044037,8.852403,0.000000,3.853585
1985-05-01,4.889708,6.129089,6.008080,7.616769,2.486633,4.971960,4.467474,2.988915,5.875009,5.654166,4.345630,4.456984
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-07-01,15.555022,20.336566,21.997676,11.643674,24.120781,12.594630,23.710592,21.247733,11.072076,153.256542,2.890518,16.911940
2025-08-01,13.092266,14.640058,15.653484,8.418171,20.877801,12.279955,17.984860,12.235830,7.244518,123.961528,0.472820,16.860247
2025-09-01,17.034746,17.071066,18.498564,10.394802,24.883883,10.725879,23.915877,10.481822,4.994681,171.246877,1.385426,14.538229
2025-10-01,11.135859,17.794064,18.834881,11.037099,35.054845,13.392293,32.969814,14.853939,5.839378,116.752884,3.023492,14.070908
2025-11-01,11.163006,19.308495,20.551080,14.429557,26.626952,12.860967,31.555698,12.869644,4.042397,145.526842,1.681921,14.660322

In [27]:
uncertainty_factors_daily.to_csv("uncertainty factors daily.csv")