In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#from sklearn.preprocessing 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostRegressor
from sklearn.linear_model import LogisticRegression, Lasso
from sklearn.metrics import root_mean_squared_error

In [ ]:
daily_volatility_indices = pd.read_csv("df.csv")
daily_volatility_indices = daily_volatility_indices.set_index("Date")

In [ ]:
daily_volatility_commodity = pd.read_csv("df_cm.csv")

In [56]:
daily_vol_cl = daily_volatility_commodity.iloc[:,0:2]
daily_vol_cl = daily_vol_cl.set_index("Date")

In [ ]:
daily_volatility_indices

,^GSPC,^DJI,^IXIC,^FTSE,^GDAXI,^FCHI,^IBEX,^N225
Date,,,,,,,,
2024-07-16,0.000787,0.002770,0.001217,0.001351,0.001530,0.002025,0.002452,0.000732
2024-07-17,0.001814,0.002080,0.003628,0.001249,0.001372,0.001786,0.002082,0.000738
2024-07-18,0.002007,0.002257,0.003442,0.001366,0.001414,0.001824,0.001899,0.000732
2024-07-19,0.001843,0.002171,0.003064,0.001453,0.001455,0.001940,0.001920,0.000827
2024-07-22,0.001875,0.001975,0.003115,0.001465,0.001540,0.001970,0.001850,0.000786
...,...,...,...,...,...,...,...,...
2025-07-08,0.002618,0.002379,0.003361,0.001849,0.002474,0.002401,0.002325,0.001698
2025-07-09,0.002614,0.002375,0.003356,0.001847,0.002472,0.002399,0.002327,0.001695
2025-07-10,0.002609,0.002371,0.003350,0.001847,0.002467,0.002395,0.002323,0.001692
2025-07-11,0.002604,0.002368,0.003344,0.001844,0.002465,0.002392,0.002321,0.001690
2025-07-14,0.002600,0.002364,0.003338,0.001842,0.002463,0.002389,0.002319,0.001688

In [57]:
dataset = pd.merge(daily_volatility_indices, daily_vol_cl, on= "Date")
dataset

,^GSPC,^DJI,^IXIC,^FTSE,^GDAXI,^FCHI,^IBEX,^N225,CL=F
Date,,,,,,,,,
2024-07-16,0.000787,0.002770,0.001217,0.001351,0.001530,0.002025,0.002452,0.000732,0.002812
2024-07-17,0.001814,0.002080,0.003628,0.001249,0.001372,0.001786,0.002082,0.000738,0.002811
2024-07-18,0.002007,0.002257,0.003442,0.001366,0.001414,0.001824,0.001899,0.000732,0.002846
2024-07-19,0.001843,0.002171,0.003064,0.001453,0.001455,0.001940,0.001920,0.000827,0.002881
2024-07-22,0.001875,0.001975,0.003115,0.001465,0.001540,0.001970,0.001850,0.000786,0.002961
...,...,...,...,...,...,...,...,...,...
2025-07-08,0.002618,0.002379,0.003361,0.001849,0.002474,0.002401,0.002325,0.001698,0.004394
2025-07-09,0.002614,0.002375,0.003356,0.001847,0.002472,0.002399,0.002327,0.001695,0.004391
2025-07-10,0.002609,0.002371,0.003350,0.001847,0.002467,0.002395,0.002323,0.001692,0.004389
2025-07-11,0.002604,0.002368,0.003344,0.001844,0.002465,0.002392,0.002321,0.001690,0.004388
2025-07-14,0.002600,0.002364,0.003338,0.001842,0.002463,0.002389,0.002319,0.001688,0.004388

In [91]:
y = dataset["CL=F"].to_frame()
x = dataset.iloc[:,0:8]

y

                CL=F
Date
2024-07-16  0.002812
2024-07-17  0.002811
2024-07-18  0.002846
2024-07-19  0.002881
2024-07-22  0.002961
...              ...
2025-07-08  0.004394
2025-07-09  0.004391
2025-07-10  0.004389
2025-07-11  0.004388
2025-07-14  0.004388

[257 rows x 1 columns]

In [99]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.pipeline import make_pipeline

In [100]:
x_train ,x_test, y_train, y_test = train_test_split(y,x)

In [ ]:
Decision_reg = DecisionTreeRegressor(
    max_depth=3,
    max_leaf_nodes=5,
    min_impurity_decrease=0.01,
    random_state=42
)

model = Decision_reg.fit(x_train, y_train)

In [110]:
y_predicted = model.predict(x_test)

In [ ]:
#y_true = 
err = root_mean_squared_error(y_pred = y_predicted, y_true = y_test)
err

0.00032524454926647907

In [ ]:
pipeline = make_pipeline(PolynomialFeatures(),

SHAP

In [96]:
DecisionTree = DecisionTreeClassifier(
    max_depth=4,
    criterion="gini",
    min_samples_leaf=5,
    min_impurity_decrease=0.01
)

model = DecisionTree.fit(x_train, y_train)
model

ValueError: Unknown label type: continuous-multioutput. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.