In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import datetime as dt
from datetime import timedelta

In [4]:
demand_factors_weekly = pd.read_csv("demand factors/demand_factors_weekly.csv")
financial_factors_weekly = pd.read_csv("financial factors/weekly_financial_factors.csv")
implied_vol_indices_weekly = pd.read_csv("implied vol indices/weekly_implied_volatility_indices.csv")
brent_weekly = pd.read_csv("prices/weekly_realized_volatility_Brent.csv")
supply_factors_weekly = pd.read_csv("supply factors/weekly_crude_oil_supply.csv")
uncertainty_factors_weekly = pd.read_csv("uncertainty factors/uncertainty factors weekly.csv")

In [9]:
y = pd.read_csv("prices/weekly_realized_volatility_WTI.csv")
y.set_index("Date", inplace=True)
y

            RV_WTI_week
Date
1987-05-24     1.694678
1987-05-31     0.680510
1987-06-07     1.638344
1987-06-14     0.998714
1987-06-21     2.015020
...                 ...
2025-11-09     1.831674
2025-11-16     2.340390
2025-11-23     3.233335
2025-11-30     1.800850
2025-12-07     1.507864

[2012 rows x 1 columns]

In [12]:
y.reset_index(inplace =True)
y['Date'] = pd.to_datetime(y['Date'])
date = y['Date'].dt.to_period('M').to_frame()
date

         Date
0     1987-05
1     1987-05
2     1987-06
3     1987-06
4     1987-06
...       ...
2007  2025-11
2008  2025-11
2009  2025-11
2010  2025-11
2011  2025-12

[2012 rows x 1 columns]

In [6]:
demand_factors_weekly

            Date  Imports_US  Imports_SPR  PPI_commodity  Consumption_US
0     1913-01-05         0.0          0.0      12.000000               0
1     1913-01-12         0.0          0.0      12.042857               0
2     1913-01-19         0.0          0.0       0.000000               0
3     1913-01-26         0.0          0.0       0.000000               0
4     1913-02-02         0.0          0.0       0.000000               0
...          ...         ...          ...            ...             ...
7709  2025-10-19      5918.0          0.0       0.000000               0
7710  2025-10-24         0.0          0.0       0.000000           21281
7711  2025-10-26      5051.0          0.0       0.000000               0
7712  2025-10-31         0.0          0.0       0.000000           20356
7713  2025-11-02      5924.0          0.0       0.000000               0

[7714 rows x 5 columns]

In [7]:
financial_factors_weekly

,Date,GBPUSD=X,GC=F,HG=F,JPY=X,USDEUR=X,ZW=F,^GSPC,Fed_Funds_Rate
0,2003-12-07,0.002116,0.002295,0.003567,-0.003566,-0.004569,-0.003277,-0.002010,0.2450
1,2003-12-14,0.001639,0.001490,0.003606,0.000129,-0.001498,-0.004768,0.002394,0.2450
2,2003-12-21,0.002045,-0.000083,0.007933,0.000057,-0.001713,0.000462,0.002707,0.2450
3,2003-12-28,0.000776,0.001512,0.000141,-0.000482,-0.000755,-0.014617,0.001327,0.2450
4,2004-01-04,0.002439,0.001650,0.003213,-0.001003,-0.002393,0.022163,0.002301,0.2500
...,...,...,...,...,...,...,...,...,...
1139,2025-10-05,0.001649,0.005551,0.014225,-0.003642,-0.001065,-0.001677,0.002162,1.0225
1140,2025-10-12,-0.002109,0.004969,-0.008216,0.007796,0.002731,-0.006568,-0.004841,1.0225
1141,2025-10-19,0.002108,0.010713,0.003716,-0.003743,-0.002283,0.002109,0.003407,1.0225
1142,2025-10-26,-0.001763,-0.002930,0.006564,0.003290,0.001402,0.003491,0.003819,1.0225
1143,2025-11-02,-0.002536,-0.006630,-0.000971,0.001710,0.000790,0.008351,0.001450,0.9700

In [5]:
y = pd.read_csv("prices/weekly_realized_volatility_WTI.csv")
y.set_index("Date", inplace=True)
y

            RV_WTI_week
Date
1987-05-24     1.694678
1987-05-31     0.680510
1987-06-07     1.638344
1987-06-14     0.998714
1987-06-21     2.015020
...                 ...
2025-11-09     1.831674
2025-11-16     2.340390
2025-11-23     3.233335
2025-11-30     1.800850
2025-12-07     1.507864

[2012 rows x 1 columns]